name: Fabric Server Full Test
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Current Java LTS & minimum supported by Minecraft
        java: [17]
        # and run on Linux
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: build/libs/
  runServer:
    strategy:
      matrix:
        # Current Java LTS & minimum supported by Minecraft
        java: [17]
        # and run on Linux
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 20 # Fail after 20 minutes

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

        # Removes the default MySQL server
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please do not remove it

        # Runs a MariaDB SQL server that plugin can interact with
      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8mb4' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8mb4_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mariadb version: '10.8.3' # Optional, default value is "latest". The version of the MariaDB
          mysql database: 'test' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.ROOT_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: ${{ secrets.DATABASE_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"

      # Downloads all needed files and runs a fabric server whit plugin
      - name: "Run Fabric Tests"
        uses: Drhampust/Fabric-Minecraft-SQL-Testing@main