name: Fabric CI
on: [pull_request, push]

jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 17 ] # Build on Java 17

    timeout-minutes: 20 # Fail after 20 minutes

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: "Run Fabric Tests"
        uses: ValkyrienSkies/Minecraft-Architectury-Testing@master
        with:
          serverType: "fabric"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: Builds
          path: build/libs